### ISSUE TITLE
collate all shapefiles

### ISSUE THREAD

**Issue by r-leyshon** [datasciencecampus/transport-performance-docker#15]
for submission to ONS geoportal

**Comment by ethan-moss** [comment]
@r-leyshon - could we please move this issue/feature request to a different repo? We should keep this docker repo purely for the end to end pipeline. Combing results into shapefiles isn't a feature we need to introduce into the docker image, and would clutter the codebase.

**Comment by r-leyshon** [comment]
no worries. happy to move.
